version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        expose:
            - 8000

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        depends_on:
            - web